// const express = require('express');
// const Meeting = require('../models/Meeting');
// const { sendMeetingSummary } = require('../services/resend');
// const authMiddleware = require('../middleware/auth');
// const router = express.Router();

// // ── EMAIL EXPORT ──────────────────────────────────────
// router.post('/export/email/:id', authMiddleware, async (req, res) => {
//   const { toEmail } = req.body;

//   if (!toEmail) {
//     return res.status(400).json({ error: 'Please provide an email address.' });
//   }

//   try {
//     const meeting = await Meeting.findOne({
//       _id: req.params.id,
//       userId: req.user.id
//     });

//     if (!meeting) {
//       return res.status(404).json({ error: 'Meeting not found.' });
//     }

//     await sendMeetingSummary({
//       toEmail,
//       meetingTitle: meeting.title,
//       summary: meeting.summary,
//       decisions: meeting.decisions,
//       tasks: meeting.tasks
//     });

//     res.json({ success: true, message: `Summary sent to ${toEmail}` });
//   } catch (err) {
//     console.error('Email export error:', err.message);
//     res.status(500).json({ error: err.message });
//   }
// });

// // ── MARKDOWN EXPORT ───────────────────────────────────
// router.get('/export/markdown/:id', authMiddleware, async (req, res) => {
//   try {
//     const meeting = await Meeting.findOne({
//       _id: req.params.id,
//       userId: req.user.id
//     });

//     if (!meeting) {
//       return res.status(404).json({ error: 'Meeting not found.' });
//     }

//     const taskLines = meeting.tasks
//       .map(t => `- [ ] **${t.task}** — ${t.assignee} — _${t.deadline}_`)
//       .join('\n');

//     const decisionLines = meeting.decisions
//       .map(d => `- ${d}`)
//       .join('\n');

//     const markdown = `# ${meeting.title}

// **Date:** ${new Date(meeting.createdAt).toLocaleString()}

// ---

// ## Summary

// ${meeting.summary}

// ---

// ## Key Decisions

// ${decisionLines || 'No decisions recorded.'}

// ---

// ## Action Items

// ${taskLines || 'No tasks recorded.'}

// ---

// ## Full Transcript

// ${meeting.transcript}

// ---

// _Generated by MeetingAI_
// `;

//     res.setHeader('Content-Type', 'text/markdown');
//     res.setHeader('Content-Disposition', `attachment; filename="${meeting.title.replace(/\s+/g, '-')}.md"`);
//     res.send(markdown);
//   } catch (err) {
//     console.error('Markdown export error:', err.message);
//     res.status(500).json({ error: err.message });
//   }
// });

// module.exports = router;


// ------------------

router.get('/export/markdown/:id', async (req, res) => {
  try {
    const jwt = require('jsonwebtoken');
    const token = req.headers['authorization']?.split(' ')[1] || req.query.token;
    if (!token) return res.status(401).json({ error: 'No token.' });
    const decoded = jwt.verify(token, process.env.JWT_SECRET);

    const meeting = await Meeting.findOne({
      _id: req.params.id,
      userId: decoded.id
    });

    if (!meeting) return res.status(404).json({ error: 'Meeting not found.' });

    const taskLines = meeting.tasks
      .map(t => `- [ ] **${t.task}** — ${t.assignee} — _${t.deadline}_`)
      .join('\n');

    const decisionLines = meeting.decisions
      .map(d => `- ${d}`)
      .join('\n');

    const markdown = `# ${meeting.title}

**Date:** ${new Date(meeting.createdAt).toLocaleString()}

---

## Summary

${meeting.summary}

---

## Key Decisions

${decisionLines || 'No decisions recorded.'}

---

## Action Items

${taskLines || 'No tasks recorded.'}

---

## Full Transcript

${meeting.transcript}

---

_Generated by MeetingAI_
`;

    res.setHeader('Content-Type', 'text/markdown');
    res.setHeader('Content-Disposition', `attachment; filename="${meeting.title.replace(/\s+/g, '-')}.md"`);
    res.send(markdown);
  } catch (err) {
    console.error('Markdown export error:', err.message);
    res.status(500).json({ error: err.message });
  }
});
